[package]
name = "graveler-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "2.1.0"
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "my_benchmarks"
harness = false

